### ISSUE TITLE
Add support for query strings without values

### ISSUE THREAD

**Issue by clintkelly** [jamielennox/requests-mock#101]
Currently if I try to mock calls to the same URI with two different query params (without values), I always get the response from the most-recently-defined mock.

Here is an example URL: `http://foo.com/bar?baz`

I used a debugger with a test using a URL like this. The constructor correctly captures the query param:

```
>>> urlparse('http://foo.com/bar?baz')
ParseResult(scheme='http', netloc='foo.com', path='/bar', params='', query='baz', fragment='')
```

So in this case, the value for `self._query` in the `_Matcher` instance will be just `'baz'`:
https://github.com/jamielennox/requests-mock/blob/cb894f1f822b3bbeb9be5b0b12dd2f27c7b6399b/requests_mock/adapter.py#L103

However, the later code that does the actual matching assumes k/v pairs for query strings. In particular, this line:
```
        matcher_qs = urlparse.parse_qs(self._query)
```
will return an empty dict:
```
>>> parse_qs('baz')
{}
```

Therefore, if I cannot mock calls to two separate URLs that differ only by query params without values.

I think we can fix this pretty easily by changing the argument to the call to `parse_qs`:
```
>>> parse_qs('baz', keep_blank_values=True)
{'baz': ['']}
```

Happy to submit a PR if you like.

**Comment by jamielennox** [comment]
Yea, it's not intentionally dropped. if it's as simple as adding the `keep_blank_values` param that should be backwards compatible and fine.

I'll try and find some time in the next few days, but I'm happy to accept a PR well (with a test :))
