### ISSUE TITLE
Assign custom url in the mocked response

### ISSUE THREAD

**Issue by NickSchimek** [jamielennox/requests-mock#102]
Is there a way to define the url to be assigned to the `url` attribute in the response?

If not, would it be possible to add it in?

Thanks, really great tool you have here!

**Comment by NickSchimek** [comment]
To add a bit of context: the URL I am mocking always returns a 200 status code regardless if it redirects or other scenario... 
In my code I use the response.url to check if it was successful instead of status_code. 

When I create a mock for `fake_url` then the response.url will still be `fake_url`, but I need a way to say the response should be `fake_url_redirected`. Like the way I can state which status_code should be returned. For my it would be handy to state which url should be returned. 

I'm not sure if this is something that is doable while keeping requests-mock current behavior in place. What do you think?

**Comment by jamielennox** [comment]
Hey, sorry for the delay in replying. 

Just doing a quick scan through requests to see what's actually possible there. From a pure HTTP perspective I don't know off the top of my head if there's such a thing as a response url. I've found where it gets set in requests: https://github.com/kennethreitz/requests/blob/7fd9267b3bab1d45f5e4ac0953629c5531ecbc55/requests/adapters.py#L278-L281 but it looks to me like it would be a straight copy of what you provided in the request. 

If you use requests-mock to provide a series of redirects, like actually mock out a series of 301s that end up at a 200 that URL is set correctly (been a while, but i'm pretty sure). But that doesn't appear to be what you're asking.

**Comment by jamielennox** [comment]
Pressed the button before i intended there.

I'm guessing that this API is a little broken and not one that you want to name publically - that's fine, the advantage of mocking is you can test for weird and difficult scenarios so i'm alright with the idea.

Can you give me a more detailed, possibly code snippet of how the API responds normally? Just trying to process how something can both redirect and return a 200.

**Comment by NickSchimek** [comment]
Thanks for the response!

Our software is using `requests` to login to an external site and then it parses some data. What we would like to do is mock the login, which we can, however our code says the login is unsuccessful; because as you stated the url is a straight copy of what's provided in the request. 
Here is where we're checking a successful login. 
https://github.com/codeforpdx/recordexpungPDX/blob/master/src/backend/expungeservice/crawler/crawler.py#L67
And here is the login method.
https://github.com/codeforpdx/recordexpungPDX/blob/master/src/backend/expungeservice/crawler/crawler.py#L20
Also here is a code snippet trying to login to the site with a bad password and a good password. You can see the status_code remains the same, but the response url is different.
```
>>> import requests
>>> from expungeservice.crawler.request import *
>>> session = requests.Session()
>>> url = URL.login_url()

# Trying to login with bad password.
# Return the login url and 200 status code
>>> payload = Payload.login_payload('username', 'bad-password')
>>> response = session.post(url, data=payload)

>>> response.status_code
200
>>> response.url
'https://publicaccess.courts.oregon.gov/PublicAccessLogin/login.aspx'

# Logging in with good password
# Returns a default url and 200 status code
>>> payload = Payload.login_payload('username', 'good-password')
>>> response = session.post(url, data=payload)

>>> response.status_code
200
>>> response.url
'https://publicaccess.courts.oregon.gov/PublicAccessLogin/default.aspx'
>>>
```

**Comment by jamielennox** [comment]
Cool, I think what you're seeing is that the `/login.aspx` is returning you a redirect and requests is handling it under the hood. You'll be able to see it in `response.history` which will show you the redirect chain. 

Here's an example that has the same behaviour you're seeing: 

```python
import requests
import requests_mock


session = requests.Session()

LOGIN_URL = 'https://publicaccess.courts.oregon.gov/PublicAccessLogin/login.aspx'
HOME_URL = 'https://publicaccess.courts.oregon.gov/PublicAccessLogin/default.aspx'


with requests_mock.mock() as m:
    # the order or these mocks is important because they're evaluated in most
    # recent first, so the first declared has to be the 'default' case.
    m.post(LOGIN_URL,
           status_code=401,
           text='Unauthorized')

    m.post(LOGIN_URL,
           status_code=301,
           request_headers={'Authorization': 'Bearer ABCD'},
           headers={'Location': HOME_URL},
           text='Redirecting')

    m.get(HOME_URL,
          status_code=200,
          text='HOME PAGE')

    good_resp = session.post(LOGIN_URL,
                             headers={'Authorization': 'Bearer ABCD'})

    bad_resp = session.post(LOGIN_URL,
                            headers={'Authorization': 'Bearer XYZ'})

    print("GOOD RESPONSE:")
    print("  URL: %s" % good_resp.url)
    print("  TEXT: %s" % good_resp.text)
    print("  HISTORY: %d" % len(good_resp.history))
    for r in good_resp.history:
        print("    * %d - %s" % (r.status_code, r.url))

    print("")

    print("BAD RESPONSE:")
    print("  URL: %s" % bad_resp.url)
    print("  TEXT: %s" % bad_resp.text)
    print("  HISTORY: ")
    for r in bad_resp.history:
        print("    * %d - %s" % (r.status_code, r.url))
```

```
GOOD RESPONSE:
  URL: https://publicaccess.courts.oregon.gov/PublicAccessLogin/default.aspx
  TEXT: HOME PAGE
  HISTORY: 1
    * 301 - https://publicaccess.courts.oregon.gov/PublicAccessLogin/login.aspx

BAD RESPONSE:
  URL: https://publicaccess.courts.oregon.gov/PublicAccessLogin/login.aspx
  TEXT: Unauthorized
  HISTORY:
```

**Comment by NickSchimek** [comment]
Wow! Your awesome! Thank you so much for the detailed response. And Thank you for teaching me this. 😄
