### ISSUE TITLE
Impossible to use array mocking of request_headers

### ISSUE THREAD

**Issue by papadeltasierra** [jamielennox/requests-mock#115]
`requests_mock` allows arrays of GET (say) responses to be defined using an array syntax but neither `request_headers` nor `complete_qs` are allowed in this array.  Seems that there is no way to configure a set of different `request_headers` or `complete_qs` requirements for multiple GETs.

**Comment by jamielennox** [comment]
I'll look into this, but that doesn't seem like something you should want to do.

Those parameters you mention are matching parameters, so we use those to check whether we should trigger the responses in this mock.

Response arrays are used to return different responses to the same mock so you can test a changing response.

We define the match once and then the array of responses to return, if you need to change those parameters you'd define a different mock for them.

**Comment by jamielennox** [comment]
Maybe post what you're trying to do.

**Comment by papadeltasierra** [comment]
Jamie, I'm mocking my 'product under test' sending what I expect to be two almost identical GET requests but with the key difference is that they both carry an authentication header and this header's value is different on the two requests.  The first is out-of-date and I mock rejecting that GET but the second is updated and I mock accepting that and responding with the requested resource. Currently I an defining an array of two GET responses, I want to be able to define a matching array of request headers to be checked to confirm that I'm receiving the correct header values in each GET request.
Or... are you saying that I should be defining the mocks are two different GET mocks?  Note that I have to define both at the same time in my test code as the processing between these mocks is all internal to my 'product under test' and thre is no place that I can 'define and test using mock, now create and test second mock' in my test code - I have to define both mocks and then 'hit Go!'.

**Comment by papadeltasierra** [comment]
Aha - the 'Or...' was exactly what I should have been doing. The request-headers filter the mock to determine what response should be sent so in my case, two **different** mocks.  And if I want to send multiple responses to identical GETs (with identical headers) I can do this providing I add the request_headers **after** the definition of the array of response.
Apologies for not reading the docs closely enough.

**Comment by jamielennox** [comment]
No worries. There's a couple of ways to do this, but 2 seperate mocks I think it's the clearest.

Just as a heads up, the order you define mocks here often matters because the first one to match will be returned, so mocks with more specific parameters should be defined first.
