### ISSUE TITLE
Response reason should be set based on status_code

### ISSUE THREAD

**Issue by jacobbogdanov** [jamielennox/requests-mock#118]
The `requests.exceptions.HTTPError` message value produced by calling `requests.Response.raise_for_status()` is not consistent when using `requests_mock`.

current behavior: (assuming there is a web server running on `localhost:443`)
```python
>>>
>>> import requests
>>> requests.get("https://localhost/not-found").raise_for_status()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    requests.get("https://localhost/not-found").raise_for_status()
  File "python3.8/site-packages/requests/models.py", line 967, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://localhost/not-found
>>>
>>>
>>>
>>>
>>> import requests_mock
>>> with requests_mock.Mocker() as m:
...     m.get("https://localhost/not-found", status_code=404)
...     requests.get("https://localhost/not-found").raise_for_status()
... 
<requests_mock.adapter._Matcher object at 0x10898e550>
Traceback (most recent call last):
  File "<input>", line 3, in <module>
    requests.get("https://localhost/not-found").raise_for_status()
  File python3.8/site-packages/requests/models.py", line 967, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: None for url: https://localhost/not-found
>>>
```

So what should've been:
```
404 Client Error: Not Found for url: https://localhost/not-found
```
ended up being
```
404 Client Error: None for url: https://localhost/not-found
```

The message is _almost_ identical, but when run using `requests_mock` the `reason` on the `requests.Response` object is never set, so `None` is printed in the message.

I know that the mock accepts a `reason` argument, but to make it easier to use the caller shouldn't need to specify the `reason` as the default behavior should be to derive the reason from the `status_code`.

Both the stdlib (python3.5+) and the `requests` library have this mapping
https://docs.python.org/3/library/http.html?highlight=httpstatus#http.HTTPStatus
```python
reason = http.HTTPStatus(status_code).phrase
```

https://requests.readthedocs.io/en/master/api/#status-code-lookup
(although this looks like the opposite mapping: name -> code.)

**Comment by jamielennox** [comment]
Hi, 

Yep, I agree. I'll try and add this next week unless you get to it first. I know py27 is EOL but I'm aiming to not break compat at this point unless I have to so if you know a good method a PR its welcomed.

**Comment by jamielennox** [comment]
Right - i remember why this is problematic. Requests isn't involved at all in the setting of reason strings. They are embedded in the http packet themselves and requests is simply passing it through. 

It probably still makes more sense to use the standard phrases here by default.
