### ISSUE TITLE
_IOReader causes infinite loop with response.iter_content(None)

### ISSUE THREAD

**Issue by ergoithz** [jamielennox/requests-mock#124]
With `stream=True`, when using `requests.Response.iter_content` as in `response.iter_content(None)`, entering the requests urllib3 stream codepath, `urllib3.response.Response` will end calling `_IOReader.read` without arguments. That will cause `_IOReader.closed` to never be updated to `True` so `urllib3.Response.stream` will iterate indefinitely, propagating to `requests.Response.iter_content`, and hanging consumers in an infinite loop.

Tested with `requests==2.22.0` `urllib3==1.25.8` `requests-mock==1.7.0`.

**Comment by jamielennox** [comment]
Hi, thanks for the report. That's deep in the weeds and realistically I've not used the streaming features much so I have no doubt you've hit a real problem. 

Can you give me a test case that I can look into with this please? The simple example I tried just then for streaming (current master) looks like: 


```python 
import requests
import requests_mock

with requests_mock.mock() as m:
    m.get('https://httpbin.org/image/jpeg', text='hello world')
    resp = requests.get('https://httpbin.org/image/jpeg', stream=True)

for i, c in enumerate(resp.iter_content()):
    print(c)
```
```sh
b'h'
b'e'
b'l'
b'l'
b'o'
b' '
b'w'
b'o'
b'r'
b'l'
b'd'
```

which seems correct to me.

**Comment by jamielennox** [comment]
ah - i should have read a bit closer. Adding `None` to iter_content hangs forever where it works on requests.

**Comment by ergoithz** [comment]
Wow, @jamielennox, that was a blazing fast response (and fix).
