### ISSUE TITLE
Needed feature: partial or pattern matching of url

### ISSUE THREAD

**Issue by cowlinator** [jamielennox/requests-mock#129]
According to the documentation, `requests_mock.mock().get()` needs to be called for every single absolute URL path that my module may make a request to while being tested.  It turns out that for my use case, this is a pretty huge number of URLs.  

Example: 
```
with requests_mock.mock() as mock_req:
    mock_req.get("https://a.particular.domain/00001", text="hi")
    mock_req.get("https://a.particular.domain/00002", text="hi")
    mock_req.get("https://a.particular.domain/00003", text="hi")
    # etc.
```

But the functionality I need is very simple:  every request to `https://a.particular.domain` , regardless of path, should return the exact same data.

I'd really like to see some kind of regex or glob pattern matching for URLs.  Or, if that is too complex to implement, I'd like to be able to specify a domain without a path.

Example: 
```
with requests_mock.mock() as mock_req:
    mock_req.get("a.particular.domain", text="hi")
```

**Comment by jamielennox** [comment]
Hi @cowlinator, 

There are a number of ways that this can be controlled in the documentation at: https://requests-mock.readthedocs.io/en/latest/matching.html

The easiest way to solve this is just a regexp: 

```
import re
import requests
import requests_mock

with requests_mock.mock() as mock_req:
    mock_req.get(re.compile('https://a.particular.domain/.+'), text="hi")

    for i in range(0, 5):
        resp = requests.get('https://a.particular.domain/%d' % i)
        assert 'hi' == resp.text

    assert mock_req.call_count == 5

print("done")
```

**Comment by cowlinator** [comment]
You are correct.  I had a hard time finding this piece of documentation.
