### ISSUE TITLE
Closed stream after reading 0 bytes

### ISSUE THREAD

**Issue by mhugo** [jamielennox/requests-mock#144]
Hi, there seems to be a strange behavior with `stream=True` when trying to read first 0 bytes. Calls to `read` that follow return an empty content.

(detected when using `ijson.items` on the returned stream which [calls read(0) first to determine the content type](https://github.com/ICRAR/ijson/blob/master/ijson/compat.py#L53) ).

Code to reproduce:
```python
import requests_mock
import requests

content = b'blah'
with requests_mock.mock() as m:
    m.get("http://test", content=content)
    res = requests.get("http://test", stream=True)
    res.raw.read(0)
    r = res.raw.read()
    print(r)
    assert r == content
```

**Comment by jamielennox** [comment]
Hmm, this seems to have been a problem with faking whether a stream was closed or not: 

https://github.com/jamielennox/requests-mock/blob/1b9a732fe842d4ac59d23eb85d1db34360d08745/requests_mock/response.py#L122-L128

I think it's probably reasonable here to test for count == 0 and return empty without closing the stream.
