### ISSUE TITLE
Update on project maintenance

### ISSUE THREAD

**Issue by ssbarnea** [jamielennox/requests-mock#148]
I came to request-mock after searching for a good mocker for requests. Still, looking at the project I see lots of PRs not dealt with and that the project depends on a single person.

Thus it would better to know if better to know if there are good reasons to adopt it or if other alternatives like https://github.com/getsentry/responses could prove to be a better long term bet (more users and apparently more active).

**Comment by jamielennox** [comment]
So I'll cop to some of that, I'm behind on PRs and yea, it's mostly just me looking at them. I'm not doing much python day to day any more. 

However as things stand the library has only been needing small feature tweaks for the last year or two. There'll have to be a big effort when requests 3 is launched, but i'd say it's a sign of a good library that has largely just worked for the last few years.
