### ISSUE TITLE
1.9.0/1.9.1 - Breaks compatibility by double quoting characters.

### ISSUE THREAD

**Issue by jamielennox** [jamielennox/requests-mock#170]
As part of #158, i took the easy way to quote a string and sent it through urlparse.quote merged as part of #162. However if you already have a quoted string (which you would have to have this work until now) this will double quote it and break.  

This is a compatibility break and a general bug - sorry, that's my mistake. 

I think the right solution here is to do the same thing requests does, so we should use the same quoting logic rather than the simplistic case.

**Comment by jamielennox** [comment]
I'd prefer to take the option to update this to use the same function as requests (as per #169), rather than revert. @m-melis @ktdreyer @OrangeDog - can you chime in if this will work for you?

**Comment by Cheaterman** [comment]
Sounds good to me - the way I discovered the original issue was with
spaces, I then foolishly assumed requests was using urllib.quote which you
then implemented 😅.

Sounds like the proper fix is to use the exact same mechanism as requests
itself and I'm all for it!

**Comment by jamielennox** [comment]
Released as 1.9.2.

Apologies for the break, this was not a very smooth release and i'll be more careful in future,

**Comment by ktdreyer** [comment]
No problem. requests-mock is a really valuable tool. It's great to see this fixed so quickly.
