### ISSUE TITLE
Drop compatibility with old pytest versions?

### ISSUE THREAD

**Issue by adamchainz** [jamielennox/requests-mock#172]
I'm testing a package on Python 3.10, where `import distutils` raises a `DeprecationWarning`. I run my tests with `-W error::DeprecationWarning` because I don't want my package to trigger warnings for users.

requests-mock's pytest plugin uses `distutils`, which then triggers an exception from the warning filter. The surrounding `try / except` is thus triggered, marking the pytest version as being <2.9 despite the error being just from a deprecation warning:

https://github.com/jamielennox/requests-mock/blob/850671f958afd287c2dbce7420f670215892314f/requests_mock/contrib/_pytest_plugin.py#L13-L20

Pytest 3.0 was released nearly 5 years ago: https://docs.pytest.org/en/latest/changelog.html#id1313

I think it would be fine to drop the old compatibility paths at this point.

If not, it would be nice to rewrite this without `distutils`.

**Comment by jamielennox** [comment]
Merged - thanks very much. I've been behind on these type of fixes.

**Comment by matthewfeickert** [comment]
:wave: Hi and thanks for making `requests-mock`! Following up on Adam's points, are there any plans to have a new release that might include PR #189 and PR #263? These would be nice to have, especially for projects that have [`filterwarnings = ["error"]`](https://github.com/scikit-hep/pyhf/blob/e8cb58136769d8a103a4ebc0cbfe0756d8ece3fb/pyproject.toml#L79-L80) turned on for pytest and then need to apply additional filterwarnings.
