### ISSUE TITLE
Cannot use auth= ?

### ISSUE THREAD

**Issue by lingfish** [jamielennox/requests-mock#186]
Hi, I'm writing a `AuthBase` class for an API I'm using, and want to test it.  Is it not possible to use the mocker to test this?

```
kwargs = {'auth': <zzz.yyy.auth.SomethingBearerAuth object at 0x7f54e5de84e0>}
provided = [], extra = ['auth']

    def _check_body_arguments(**kwargs):
        # mutual exclusion, only 1 body method may be provided
        provided = [x for x in _BODY_ARGS if kwargs.pop(x, None) is not None]
    
        if len(provided) > 1:
            raise RuntimeError('You may only supply one body element. You '
                               'supplied %s' % ', '.join(provided))
    
        extra = [x for x in kwargs if x not in _HTTP_ARGS]
    
        if extra:
            raise TypeError('Too many arguments provided. Unexpected '
>                           'arguments %s.' % ', '.join(extra))
E           TypeError: Too many arguments provided. Unexpected arguments auth.
```

**Comment by jamielennox** [comment]
This is implying that you're passing your auth class to the mocker? You would pass the auth class to your request method and then assert that the produced request contained the auth information you would expect? 

I'm sure there was another question where i answered something related to this, but this exists on stackoverflow: https://stackoverflow.com/questions/64436423/how-to-use-request-mock-to-test-custom-authentication-handlers-with-requests
