### ISSUE TITLE
Type annotation for register_uri(text=...) doesn't support dynamic invocation

### ISSUE THREAD

**Issue by euresti** [jamielennox/requests-mock#191]
As mentioned in: https://github.com/jamielennox/requests-mock/pull/173#issuecomment-839105779

> The existing text parameter's type annotation doesn't currently support [dynamic invocation](https://requests-mock.readthedocs.io/en/latest/response.html#dynamic-response). But I elected to treat those as out of scope of this pull request.

**Comment by jamielennox** [comment]
I think this was actually covered? In each of the mock endpoints the definition is: 
```
text: Union[str, Callable[[_RequestObjectProxy, _Context], str]] = ...,
```
which is either a string, or a callable object that returns a string. 

Is there something i'm missing?

eg https://github.com/jamielennox/requests-mock/blob/0aeaecd3f43be0fc99a342fa2d6f77d9702997b1/requests_mock/mocker.pyi#L73
