### ISSUE TITLE
Request that requests-mock will be supported on python 3.10

### ISSUE THREAD

**Issue by etuzon** [jamielennox/requests-mock#197]
I request that requests-mock will be supported on python 3.10

**Comment by jamielennox** [comment]
it doesn't work?

**Comment by etuzon** [comment]
Hi

I don't see the package available on Python 3.10.

Thanks, Eyal

**Comment by jaraco** [comment]
The package installs to Python 3.10, 3.11, and 3.12 fine for me. I recommend to close unless the user reports what is not working. My guess is they were just looking for fb1bb902cbcf204561d508f9b0507b08e2fa9fb9, which wasn't released until August 2022.

**Comment by etuzon** [comment]
Hi

I dont remember which version I used, but it was probably not the latest
version, so you ca close the issue.

Thanks, Eyal
