### ISSUE TITLE
Threading.Lock causes nested test to hang

### ISSUE THREAD

**Issue by jamielennox** [jamielennox/requests-mock#201]
This is currently breaking github tests and is reproducable on my local. I don't know how it got merged without triggering the test. I'm going to revert the commits for now, they're pretty small and can go back in later.

As part of #183 we added a `threading.Lock` to the core `send()` function. This unfortunately appears to break if you have nested mockers, which i don't like but know that people do. Specifically this test: https://github.com/jamielennox/requests-mock/blob/0aeaecd3f43be0fc99a342fa2d6f77d9702997b1/tests/pytest/test_with_pytest.py#L17-L62

An easy solution I found to the problem is to use an RLock instead, but it does raise the question are there other places this could be a problem, and maybe is there a better way to reliably monkeypatch the function without needing to Lock? 

@phodge - thoughts?

**Comment by phodge** [comment]
Hi @jamielennox: Thanks for bringing this to my attention. RLock sounds like it might work, but I can't remember the code well enough to say whether it might also lead to unexpected deadlocks. I'm keen to have the threading fixes added to the next release so I will have a look at this first thing tomorrow and see if I can come up with another fix if you haven't figured something out by then. (I'm on UTC+10 so it's too late for me to look at this tonight.)

**Comment by jamielennox** [comment]
Released in 1.10.
