### ISSUE TITLE
last_request some time using the default url `test.com`

### ISSUE THREAD

**Issue by skapil** [jamielennox/requests-mock#208]
**Summary**
We have found that `requests_mock.last_request` is not fully reliable. It sometimes returns values as:
```python
requests_mock.last_request.hostname
>>> test.com
```
The issue making our test flaky. Did anyone faced the similar issue and any workaround.

**Comment by jamielennox** [comment]
I haven't seen this elsewhere. Could it be a threading issue? Any way you can provide a reproducer of this?

**Comment by skapil** [comment]
Closing this issue as it's not reproducible.
