### ISSUE TITLE
Type information for `MockerCore` methods seems incorrect

### ISSUE THREAD

**Issue by j-ulrich** [jamielennox/requests-mock#209]
The type information for the `MockerCore` class ([mocker.pyi](https://github.com/jamielennox/requests-mock/blob/master/requests_mock/mocker.pyi)) seems incorrect:

It pretends that the methods `register_uri()`, `request()`, `get()`, `post()` etc. return a `requests.Response` object. But actually, they return a `requests_mock.adapter._Matcher` object.

**Comment by jamielennox** [comment]
Hi, Thank you. I had found this one and have merged the fix in #199
