### ISSUE TITLE
Fixtures library missing in requirements.txt

### ISSUE THREAD

**Issue by jhurej** [jamielennox/requests-mock#217]
Hi,

It looks like fixtures library is missing in requirements.txt. It cause an error in my code. Adding fixtures library next to requests_mock in my repo's requirements fixed the issue but it's just a workaround. Could you please add it to your requirements.txt?
<img width="1086" alt="Screenshot 2022-11-29 at 01 41 48" src="https://user-images.githubusercontent.com/77105498/204410350-081d1830-3439-4853-867e-d0484cff312a.png">

**Comment by jamielennox** [comment]
It's there as an optional dependency, so if you add 

`requests-mock[fixture]`

to your dependency it'll bring those additional dependencies.


https://requests-mock.readthedocs.io/en/stable/fixture.html

**Comment by jhurej** [comment]
Got it, thank you
