### ISSUE TITLE
Content-Type header is not properly set for responses mocked via json argument in register_uri

### ISSUE THREAD

**Issue by jizhilong** [jamielennox/requests-mock#231]
Hi @jamielennox ,
   Thanks for your great project, it helps me a lot to simplify unit tests. 
   Recently I encountered a issue related to mock response headers, and I wonder is it by design or is it a bug? 

   For example,  the flowing case would fail:

```python
def test_response_headers(requests_mock):
    import requests
    patcher = requests_mock.get('/', json={'key': 'value'})
    response = requests.get('http://localhost/')
    assert patcher.call_count == 1
    assert response.json() == {'key': 'value'}
    assert response.headers['Content-Type'] == 'application/json'
```

with with exception like:

```

self = {}, key = 'Content-Type'

    def __getitem__(self, key):
>       return self._store[key.lower()][1]
E       KeyError: 'content-type'

../.venv/lib/python3.8/site-packages/requests/structures.py:52: KeyError
```

explicitely setting headers via `requests_mock.get('/', json={'key': 'value'}, headers={'Content-Type': 'application/json'})` works, but it will introduce more boilerplates.

**Comment by jamielennox** [comment]
hi, it was intentional - though in hindsight probably a mistake if you're using the `json=` setter. We were testing some situations where things like content-type was unset or wrong so it made sense that you specified the entire header array.

I think in a 2.0 version i'd probably fix this, but for now you're correct.

**Comment by jizhilong** [comment]
Hi, Thanks for responding, I'll close the issue now.

For now,  to reduce boilerplates, I may add a thin pytest fixture based on `requests_mock`
