### ISSUE TITLE
Clarify whether urllib3 is supported

### ISSUE THREAD

**Issue by robinaly** [jamielennox/requests-mock#235]
I am trying to mock [elasticsearch](https://elasticsearch-py.readthedocs.io/en/v8.8.2/) calls. The python library uses [urllib3](https://github.com/urllib3/urllib3). However, this doesn't seem to work. I searched the documentation but couldn't find whether the intention is to only mock calls from the requests package or also from other libraries.

**Comment by jamielennox** [comment]
requests-mock uses the adapter implementation of the requests library to mock calls. No, you need to be using requests to use requests-mock.
