### ISSUE TITLE
Dynamic headers when register_uri through requests_mock

### ISSUE THREAD

**Issue by RegisGraptin** [jamielennox/requests-mock#237]
I am currently trying to mock an url where I want to have dynamic values inside the headers of my response. 
The use case that I have is an API that doing a pagination system through the link inside the headers. 
Thus, based on the request url parameters, I want to create a new link inside the headers to defined the next url.

```python
# Defined the next link by incrementing the current id
def dynamic_headers(req, _):
    id = req.get_id_from_url(url) + 1
    return {
        "Content-Type": "application/json",
        "Link": f'/api/projects/{id};rel="next"',
    }

requests_mock.register_uri(
    "GET",
    re.compile(r"/api/projects/\d*"),
    request_headers = authorized_headers,
    headers = dynamic_headers,  # Have a dynamic headers instead of a simple dict
    json = get_json_response_from_project,
)
```
Currently I can't do that, as the `headers` value need to be a dictionary.
I would like to know if this use case is already managed inside the library, or is there another way of doing it?
Thanks for your help

**Comment by jamielennox** [comment]
the body and the headers are not considered seperate things that you would want to call out seperately. As part of the json callback you can set the headers on the context object: https://requests-mock.readthedocs.io/en/latest/response.html#dynamic-response

Is this sufficient? I think this single callback idea is better, but left me know if you have a reason it doesn't work

**Comment by jamielennox** [comment]
eg https://github.com/jamielennox/requests-mock/blob/15df8e2b85ae71afea1013b5bf9fd010623acd39/tests/test_adapter.py#L79
