### ISSUE TITLE
requests-mock v1.12.0 incorrectly installs for python 2 breaking pipelines

### ISSUE THREAD

**Issue by fervand1** [jamielennox/requests-mock#254]
Hello, the recent version released of requests-mock 1.12.0 incorrectly installs on python 2 when it is only supported on python 3 and above.
This is causing a break in ci / cd pipeline.
Metadata of the package should be  set to be downloadable only for python 3

Quick solution for now is to pin to version < 1.12.0 but can this be rectified?

**Comment by bobleckelibm** [comment]
Putting in another vote for this. I've seen this a lot recently where a project will drop PY2 support (fairly I must say) but doesn't properly reflect that in the metadata for the package and other projects with dependencies that are not explicitly pinned will start breaking. 

In our case, we _have_ to support 2.7, at least in our build pipelines. We use `~=` syntax for things like this so we would certainly get a minor update like 1.11.0 -> 1.12.0. I would expect that a change like this would either a) officially remove PY2 support or b) go to 2.0 or something like that.

If someone who works on requests-mock is here, would it be possible to yank 1.12.0 and republish with `python_requires` added to https://github.com/jamielennox/requests-mock/blob/master/setup.cfg#L28

**Comment by jamielennox** [comment]
Ah, you never get this right for everyone. I spent a lot of time looking to whether i needed to bump a major version for dropping py2 and was eventually convinced it was normal to not. 

Having said that, you're right. I didn't see `python_requires` but that should have been done. I'll fix it.

**Comment by jamielennox** [comment]
I am blocked from uploading a new package whilst pypi is locked. I'll restart the job a bit later.

**Comment by bobleckelibm** [comment]
No problem, appreciate the quick response

**Comment by jamielennox** [comment]
[1.12.1](https://pypi.org/project/requests-mock/1.12.1/) published. Please confirm it fixes the issue.

**Comment by fervand1** [comment]
@jamielennox Yes that should resolve it, but you need to yank 1.12.0

**Comment by jamielennox** [comment]
sure - done.

**Comment by fervand1** [comment]
@jamielennox Thank you!
