### ISSUE TITLE
`v1.12.1` wasn't Published on PyPI

### ISSUE THREAD

**Issue by zliang-akamai** [jamielennox/requests-mock#256]
https://pypi.org/project/requests-mock/#history

**Comment by jamielennox** [comment]
Yea, it was blocked by pypi as there was some sort of malware campaign they were fighting yesterday. 

I'll trigger it again today.

**Comment by jamielennox** [comment]
[1.12.1](https://pypi.org/project/requests-mock/1.12.1/) published
