### ISSUE TITLE
Tests failing after 1.5.1 release

### ISSUE THREAD

**Issue by Mariatta** [jamielennox/requests-mock#66]
May I know what are the the changes from 1.5.0 to 1.5.1?
I couldn't seem to find the changelog.

My tests used to pass in 1.5.0 but now failing using requests-mock 1.5.1, and the error seems to originate from request-mock.

The only change in the PR is simply updating requests-mock from 1.5.0 to 1.5.1:
https://github.com/python/miss-islington/pull/118

You can see the test output here:
https://travis-ci.org/python/miss-islington/jobs/406491092

Is there any change I need to do in the way I wrote the tests?

Thanks.

**Comment by jamielennox** [comment]
Damn, i just thought i fixed that the other way. 

The changelog unfortunately got missed in the release but is essentially just https://github.com/jamielennox/requests-mock/commit/acce6240de329869ef87efaf43560f4a6dfeafcd

Basically in centos 7 there's an old version of pytest that needed to be supported, so 1.5.1 was just supposed to be 1.5.0 with older pytest support.

Let me look into it.

**Comment by jamielennox** [comment]
I've delete the 1.5.1 release from pypi (that felt wrong, wish you could just mark as bad rather than delete), and i'll retag this as 1.5.2. 

Sorry about that, but thanks for catching it so quickly. I'm going to look into that bot.

**Comment by Mariatta** [comment]
Alright thanks for looking into this!!
