### ISSUE TITLE
Suggestion, allow mock to throw timeout exception

### ISSUE THREAD

**Issue by daliclass** [jamielennox/requests-mock#70]
Hey!

I am a long time user and have been enjoying this library. I think it would be a good idea to add a timeout to requests mock so that its easy to test the below code

```
try:
    requests.get(url, timeout=0.5)
except requests.exceptions.Timeout as timeout_exception:
    pass
    # Do something
```        
I like the idea of setting a request_timeout=0.3 on requests_mock and it throwing the exception, rather than patching the .get method on requests.

Happy to do the work if we think its a good idea?

**Comment by jamielennox** [comment]
Hi, thanks for dropping in. 

Any reason that using the existing exc= handler wouldn't work for this? Are you actually asking to sleep for the timeout (That seems kind of pointless for unit testing)?

```
requests_mock.get(url, exc=requests.exceptions.Timeout())
```

https://requests-mock.readthedocs.io/en/latest/response.html#raising-exceptions

**Comment by daliclass** [comment]
Glad I asked, thats what I want 👍 

Thanks for the library mate, great job

**Comment by jamielennox** [comment]
Awesome, issue closed, no work required :) 

Glad I could help.
