### ISSUE TITLE
can't pickle weakref objects

### ISSUE THREAD

**Issue by arossert** [jamielennox/requests-mock#78]
I have a scenario in my application where I need to pickle a requests `Response` object.
When using the original requests library the `Response` object is picklable without any issues but when using the `requests-mock` in my tests I'm getting the error.
```
TypeError: can't pickle weakref objects
```

Is there someting that I can do to make the `requests-mock` `Response` object picklable?

**Comment by jamielennox** [comment]
Hey, 

Sorry for taking a while to respond. I must admit i'd never even considered needing to pickle a response. I'm interested in what you're doing there if you want to share? 

It's a bit strange, but it doesn't affect anything in terms of functionality of the library so I'm happy to support it.
