### ISSUE TITLE
How to mock inner POST method without affecting outer POST method?

### ISSUE THREAD

**Issue by yangquan1982** [jamielennox/requests-mock#82]
There is a POST method A inside which another POST method B is called. I want to test method A by mocking method B. Don't how to deal this kind of nested POST methods scenario.

**Comment by jamielennox** [comment]
Can you give a sample of what you're trying to do? It sounds like your unit tests are calling an external API, if it's not within the process then there's no way for requests-mock to intervene.

**Comment by yangquan1982** [comment]
This is the POST request that I need to test, which will call another POST request during processing.
```
@app.route('/jira/webhooks', methods=['POST'])
def webhook():
    """
    Receives notification of Jira ticket updates

    The webhook processes the JSON object passed in the request and consults
    the settings database on whether it is in the working state or not. The
    request is then forwarded to the Gitlab webhook.
    """
    js = request.json
    issue = js['issue']
    key = issue['key']
    status = issue['fields']['status']['name']
    project = issue['fields']['project']['key']
    log.debug('Ticket: [%s] Status: [%s]', key, status)

    jira_settings = db.jira_collection()
    # determine whether or not the status is acceptable in the db settings
    is_working_state = jira_settings.find_one({
        'project': project,
        'states': {
            '$in': [status]
        }
    }, projection={'_id': False})

    data = {'is_working_state': is_working_state, 'ticket': js}
    requests.post(GITLAB_WEBHOOK, json=data)
    return jsonify(is_working_state=is_working_state)
```
My test scripts will call this `webhook`, but need to mock `requests.post(GITLAB_WEBHOOK, json=data)`

**Comment by jamielennox** [comment]
So it's going to depend on how you call the webhook in your tests, but really that situation is exactly what requests-mock is good for. 

requests-mock only mocks out the requests call within the same process. So that looks like flask and flask has a webtest-like unit test interface that you use to call the webhook from your tests. That doesn't go through the `requests` library interface and so won't be affected by requests-mock.

So it should be no problem at all - what are you seeing when you run it? How are you calling that from a test?

**Comment by yangquan1982** [comment]
```@pytest.mark.run(order=4)
def test_webhook(ip_port_4_jira_webhooks, mongodb_4_test, set_gitlab_hook):
    jira_webhooks_url = ip_port_4_jira_webhooks + '/jira/webhooks'
    r = requests.post(url = jira_webhooks_url, headers = {'Content-Type':'application/json'}, json = jira_webhook_data)
    issue = jira_webhook_data['issue']
    status = issue['fields']['status']['name']
    project = issue['fields']['project']['key']
    is_working_state = mongodb_4_test.jiras.find_one({
        'project': project,
        'states': {
            '$in': [status]
        }
    }, projection={'_id': False})
    assert r.json() == {'is_working_state':is_working_state} # check result of webhook()```
This is how I call the `jira webhook` under test. For now I just write a mock service (a dummy flask app) to replace the real `gitlab webhook` request inside the `jira webhook` method. But I still don't know how to use `requests-mock` to mock the `inner` request method which is called by the `outer` request method.

**Comment by jamielennox** [comment]
ah, right so in which case you are actually starting the application on a new port and making a request to that new service. If you were to use requests-mock there you'd only have access to the current process. 

Is this an integration test? Normally for a simple unit test (requests-mock's main target) you'd use something like: https://pytest-flask.readthedocs.io/en/latest/ and you'd test the application without spinning up a real server or new port.

**Comment by yangquan1982** [comment]
It should be a unit-test in which I have to decouple the request method under test and its sub-request method.

**Comment by jamielennox** [comment]
so in 
```
jira_webhooks_url = ip_port_4_jira_webhooks + '/jira/webhooks'
```
you're pointing the request to be made at a server that is already running and controlled outside of this unit test. The problem for requests-mock is that to mock you would have to install the mocks on whatever is launching that server. 

Think of requests-mock as a drop in replacement for requests - within the current process. As soon as you are calling a server over http like this you are executing the code in another process.

With something like pytest-flask (or most others) you create a new application object, and then make requests to it that just execute the python code from within the test process itself. If you do it this way then the only place you use the `requests` library is when you call the external service - which is what you want to mock. 

If you have control of the thing that creates the server you could likely add the mocks there, but they would live for the lifetime of the server where typically we just want the lifetime of the test.

Is this an opensource project that i can see?

**Comment by yangquan1982** [comment]
Thanks, the `pytest-flask` looks good to my situation in which I'm actually doing integration test by using unit test approach.
