### ISSUE TITLE
Support Type Hints

### ISSUE THREAD

**Issue by jamielennox** [jamielennox/requests-mock#94]
We should make an attempt to provide python type hinting support. It will need to continue to support python2.7 and I would like to figure out how it can be unit tested through mypy or something.

**Comment by jonadaly** [comment]
Seconding this suggestion - we use `mypy` extensively throughout our codebase, and typing support for `requests-mock` would be valuable to us. At the moment we need to pick between imports of private classes such as `requests_mock.adapter._Matcher`, or resorting to `Any`.

**Comment by jamielennox** [comment]
yea, there was a request for _Matcher and _Context to be public classes. I don't really like that mypy forces that, there's no reason for them to be public, but it's not a big deal in practice.

**Comment by pcorpet** [comment]
@jamielennox @jonadaly can you try out my PR? I've been using those hints for a while but always with the same pattern so it's worth running it against other pieces of code before submitting.

Also I've considered checking them with `stubtest` but I think it's not worth it: we don't need to stub all internals of `requests_mock` which makes `stubtest` complain.

**Comment by palfrey** [comment]
> @jamielennox @jonadaly can you try out my PR? I've been using those hints for a while but always with the same pattern so it's worth running it against other pieces of code before submitting.

I've just run your PR against some code I've got (non-public, so can't share links), and works perfectly :)

**Comment by jonadaly** [comment]
Your PR works for me!

**Comment by jamielennox** [comment]
Going to mark this closed by #161. If it needs to be enhanced it can be done in an incremental way.

Thanks for the input.

**Comment by jamielennox** [comment]
Released as 1.9.0

**Comment by palfrey** [comment]
> Released as 1.9.0

Awesome. Upgraded my project, deleted a bunch of internal hacky mocks :)

**Comment by pcorpet** [comment]
Thanks @jamielennox for the release, and the quick patch! It's working like a charm for us as well.
